# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

<img src="trainings1.jpg" />

## Task 0
- import numpy

In [4]:
import numpy as np

## Task 1
- print version of numpy

In [5]:
print(np)

<module 'numpy' from '/opt/conda/lib/python3.6/site-packages/numpy/__init__.py'>


## Task 2
- create 1d vector of zeros of size 10

In [6]:
vector_0=np.zeros(10)
print(vector_0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Task 3
- create 1d vector filled with ones of size 10

In [7]:
vector_1=np.ones(10)
print(vector_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Task 4
- create 1d vector filled with ones of size 10,

In [8]:
vector_1=np.ones(10)
print(vector_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [9]:
x = np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


## Task 6
- create any 1d vector, then reverce it, such that last element will be on the first position

In [10]:
vector = np.array([1, 2])
reverseVector = vector[::-1]
print(reverseVector)

[2 1]


## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [11]:
list = (0,1,2,3,4,5,6,7,8)
matrix = []

while list != []

      '\t'
      matrix.append(list[:3])
       '\t'
      list = list[3:] 
        
        
i = 0
while i < 10:
    print(i, end=' ')
    i += 1
        
        


print(matrix)

SyntaxError: invalid syntax (<ipython-input-11-0477b7a30fdb>, line 4)

## Task 8
- create 3x3 matrix filled with ones

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Task 9
- create 3x3 matrix filled with random numbers

In [13]:
np.random.random(size=(3,3))

array([[0.77362609, 0.14007029, 0.2947208 ],
       [0.37594017, 0.98037661, 0.22331323],
       [0.8650443 , 0.12116324, 0.72683169]])

## Task 10
- create 3x3x3 array filled with random numbers

In [14]:
np.random.random(size=(3,3,3))

array([[[9.58055866e-01, 7.80585596e-02, 7.35906031e-01],
        [4.61897406e-01, 5.50675683e-01, 9.76319103e-01],
        [5.01758634e-01, 8.10621420e-01, 2.45064522e-01]],

       [[4.94547789e-01, 8.46037186e-01, 4.29385102e-01],
        [2.73065124e-01, 4.61244738e-01, 1.24804421e-01],
        [5.24970487e-04, 6.66325449e-01, 6.86296559e-01]],

       [[3.95216318e-01, 1.80430422e-01, 4.91938566e-01],
        [4.67664850e-01, 4.74807658e-01, 7.10514928e-01],
        [7.69617261e-01, 4.35292498e-01, 1.12991331e-01]]])

## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [15]:
#a= np.random.random(size=(10,10))
#print(a)

#max = np.amax(a)
#print (max)

#min = np.amin(a)
#print (min)

max= np.amax(np.random.random(size=(10,10)))
print (max)

min= np.amin(np.random.random(size=(10,10)))
print (min)


0.9887261871062293
0.009696607088229059


## Task 12
- create a random 1d vector of size 30 and find average of them

In [16]:
np.mean(np.random.random(size=(30)))
#np.random.random(size=(30))

0.535621091277793

## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [46]:
a= np.ones((5,5))
b = a[1:-1]= 0
i = 1
while i < 4:
    a[i][0] = 1
    a[i][4] = 1
    i = i + 1
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

In [47]:
a= np.ones((8,8))
b = np.arange(0,8,2)
c = np.arange(1,8,2)
i = 0
while i < 8:
    if i % 2 == 0:
         a[i][b] = 0
    elif i % 2 != 0:
         a[i][c] = 0
    i = i + 1
print(a)           

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

In [77]:
#help(np.tile)
c = np.array([[0,1],
             [1,0]])
np.tile(c,(4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

In [85]:
#help(np.dot)
a=np.random.random(size=(5,3))
b=np.random.random(size=(3,2))
c = np.dot(a,b)
print(a)   
print(b)   
print(c)

[[0.66659899 0.37608111 0.21888993]
 [0.93180434 0.77471048 0.36513513]
 [0.13443807 0.0228787  0.93477831]
 [0.68796371 0.42679682 0.01437219]
 [0.95444444 0.16231022 0.18900277]]
[[0.25946216 0.89326234]
 [0.42161913 0.02054298]
 [0.57337151 0.31471849]]
[[0.45702545 0.67206231]
 [0.77775881 0.96317536]
 [0.58050294 0.41475048]
 [0.36668686 0.62782295]
 [0.42444411 0.91538628]]


## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

In [98]:
#help(np.random.random)
np.random.randint(0,11,size=100)

array([ 5,  0,  7,  4,  0,  4,  1,  2,  3,  7,  6, 10,  5,  6,  9,  9,  7,
        8,  4,  2, 10,  9,  6,  5,  2,  5,  7,  1,  9,  9,  7,  8,  1,  6,
        1, 10,  4,  1,  8, 10, 10,  5,  6, 10, 10,  9,  2,  3,  7,  7,  8,
        7,  3,  3,  4,  3,  2,  0,  4,  1,  6,  4,  5,  4,  9,  4,  1,  6,
        2,  0,  3,  0,  5,  8,  4,  9,  3,  8,  7,  3,  9,  3,  4,  5,  6,
        9,  1,  2,  8,  1,  4,  6,  3,  0,  0, 10,  8,  1,  0,  0])

## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

In [97]:
np.random.randint(0,5,size=(5,5))

array([[3, 2, 0, 2, 1],
       [2, 4, 1, 2, 1],
       [2, 4, 3, 1, 2],
       [0, 4, 1, 4, 1],
       [1, 3, 4, 0, 1]])

## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

In [95]:
np.random.randint(0,2,size=100)

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1])

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

In [96]:
np.random.randint(0,101,size=(10,2))

array([[21, 63],
       [34, 61],
       [23, 86],
       [ 2, 19],
       [52, 61],
       [66, 46],
       [12, 88],
       [61, 44],
       [37, 56],
       [51, 24]])

## Task 21
- create random 13x13 matrix, replace maximal element to zero

## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

## Task 23
- create an array of random `float` numbers and convert it to `int`

## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element