# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

<img src="trainings1.jpg" />

## Task 0
- import numpy

In [2]:
import numpy as np

## Task 1
- print version of numpy

In [3]:
print(np)

<module 'numpy' from '/opt/conda/lib/python3.6/site-packages/numpy/__init__.py'>


## Task 2
- create 1d vector of zeros of size 10

In [4]:
vector_0=np.zeros(10)
print(vector_0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Task 3
- create 1d vector filled with ones of size 10

In [5]:
vector_1=np.ones(10)
print(vector_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Task 4
- create 1d vector filled with ones of size 10,

In [6]:
vector_1=np.ones(10)
print(vector_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [8]:
x = np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


## Task 6
- create any 1d vector, then reverce it, such that last element will be on the first position

In [9]:
vector = np.array([1, 2])
reverseVector = vector[::-1]
print(reverseVector)

[2 1]


## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [54]:
list = (0,1,2,3,4,5,6,7,8)
matrix = []

while list != []

      '\t'
      matrix.append(list[:3])
       '\t'
      list = list[3:] 
        
        
i = 0
while i < 10:
    print(i, end=' ')
    i += 1
        
        


print(matrix)

SyntaxError: invalid syntax (<ipython-input-54-0477b7a30fdb>, line 4)

## Task 8
- create 3x3 matrix filled with ones

In [57]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Task 9
- create 3x3 matrix filled with random numbers

In [62]:
np.random.random(size=(3,3))

array([[0.63998938, 0.49499534, 0.4886706 ],
       [0.16426426, 0.06172749, 0.1172337 ],
       [0.31884066, 0.49991492, 0.64926861]])

## Task 10
- create 3x3x3 array filled with random numbers

In [63]:
np.random.random(size=(3,3,3))

array([[[0.3620173 , 0.51881439, 0.09000818],
        [0.65901167, 0.2732924 , 0.08900244],
        [0.54536681, 0.85555383, 0.72006884]],

       [[0.18787075, 0.90329594, 0.96127253],
        [0.87545262, 0.16342355, 0.24568489],
        [0.33697369, 0.26352788, 0.28262198]],

       [[0.35690515, 0.26931858, 0.13170062],
        [0.24292258, 0.63995879, 0.38461056],
        [0.63808346, 0.96247396, 0.40936523]]])

## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [79]:
#a= np.random.random(size=(10,10))
#print(a)

#max = np.amax(a)
#print (max)

#min = np.amin(a)
#print (min)

max= np.amax(np.random.random(size=(10,10)))
print (max)

min= np.amin(np.random.random(size=(10,10)))
print (min)


0.994271851910998
0.03146840285497321


## Task 12
- create a random 1d vector of size 30 and find average of them

In [83]:
np.mean(np.random.random(size=(30)))
#np.random.random(size=(30))

0.5541631005976286

## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [130]:
a= np.zeros((5,5))
b = a[4:] = 1
c = a[0:1] = 1

d = a[1][0] = 1
e = a[2][0] = 1
f = a[3][0] = 1

g = a[1][4] = 1
h = a[2][4] = 1
i = a[3][4] = 1

print(a)
#print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

## Task 21
- create random 13x13 matrix, replace maximal element to zero

## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

## Task 23
- create an array of random `float` numbers and convert it to `int`

## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element